# styles in this are to be used with the following decorator around
# plotting functions: @mpl.rc_context(analytic)
analytic = {
    "lines.linewidth": 3,
    "lines.linestyle": "-",
    "lines.color": "k",
    "figure.facecolor": "FFFFFF",
    "figure.figsize": (6, 5),
    "axes.labelsize": 24,
    #"axes.grid": True,
    "axes.linewidth": 2,
    "axes.titlesize": 20,
    "xtick.labelsize": 24,
    "ytick.labelsize": 24,
    "ytick.left": True,
    "ytick.right": True,
    "xtick.top": True,
    "xtick.bottom": True,
    "xtick.minor.size": 3,
    "ytick.minor.size": 1,
    "xtick.minor.width": 3,
    "ytick.minor.width": 1,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "xtick.major.size": 5,
    "ytick.major.size": 5,
    "xtick.major.width": 3,
    "ytick.major.width": 3,
    "xtick.direction": "in",
    "ytick.direction": "in",
    "xtick.major.pad": 5,
    "ytick.major.pad": 5,
    "font.family": "serif",
    #"font.serif": "Computer Modern",
}
